table 'AdventureWorks Product Categories Lookup'
	lineageTag: 577d998a-f65a-405a-9a95-a81324b578db

	column ProductCategoryKey
		dataType: int64
		formatString: 0
		lineageTag: c8570a21-9294-4a2d-8f55-1ce35c1c6e51
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: 5bef8d49-7568-4e92-8d31-030824e51421
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	partition 'AdventureWorks Product Categories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\oping\OneDrive\Desktop\Power BI Maven Analytics\AdventureWorks+Raw+Data\AdventureWorks Raw Data\AdventureWorks Product Categories Lookup.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductCategoryKey", Int64.Type}, {"CategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

